name: Deploy to Hostinger VPS with Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ipwrcbackend .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push Docker Image to Docker Hub with tag 'backend'
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/ipwrcbackend ${{ secrets.DOCKER_USERNAME }}/ipwrcbackend:backend
          docker push ${{ secrets.DOCKER_USERNAME }}/ipwrcbackend:backend

      - name: Deploy to Hostinger VPS
        uses: appleboy/ssh-action@master
        with:
          host: 149.100.156.79
          username: root
          key: ${{ secrets.SSH }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASS }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/ipwrcbackend:backend
            docker stop ipwrcbackend || true
            docker rm ipwrcbackend || true
            docker run -d -p 8080:8080 -p 8081:8081  --network=postgres-network \
              -v /project/certs:/app/keystore \
              --name ipwrcbackend ${{ secrets.DOCKER_USERNAME }}/ipwrcbackend:backend
