name: Test SSH Connection

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test SSH connection
      if: ${{ github.event_name != 'pull_request' || github.event.head.repo.full_name == github.repository }}
      run: |
        mkdir -p /github/home/.ssh
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > /github/home/.ssh/id_rsa
        chmod 600 /github/home/.ssh/id_rsa
        ssh-keyscan -H 149.100.156.79 >> /github/home/.ssh/known_hosts
        ssh -i /github/home/.ssh/id_rsa -o StrictHostKeyChecking=no root@149.100.156.79 echo "SSH connection successful"
