name: Test SSH Connection

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create SSH directory
      run: mkdir -p ~/.ssh

    - name: Test SSH connection
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 149.100.156.79 >> ~/.ssh/known_hosts
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@149.100.156.79 echo "SSH connection successful"
